services:
  backend:
    build:
      dockerfile: backend/Dockerfile
      context: .
      target: dev
    environment:
      NODE_ENV: development
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - .:/home/node/app
  frontend:
    build:
      dockerfile: frontend/Dockerfile
      context: .
      target: dev
    environment:
      API_BASE_URL: ${API_BASE_URL:-http://backend:3000}
    ports:
      - 127.0.0.1:4200:4200
    volumes:
      - .:/home/node/app
