/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated service exports
* Do not edit this file manually
*/
export { AppService } from "./app.service";
export { AuthService } from "./auth.service";
export { BalneariosService } from "./balnearios.service";
export { PuntosInteresService } from "./puntosInteres.service";
export { RolesService } from "./roles.service";
export { UsersService } from "./users.service";
